---
title: "Simply Statistics post"
author: "Amy Gill"
date: 2019-07-19
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

## Simply Statistics post

I had the pleasure of writing a guest post on the [Simply Statistics](https://simplystatistics.org/2019/07/19/more-datasets-for-teaching-data-science-the-expanded-dslabs-package/) blog today! 

The post announces an update of the [**dslabs** R package](https://cran.r-project.org/web/packages/dslabs/index.html) in collaboration with Rafael Irizarry, which adds 7 new datasets on climate change, astronomy, life expectancy, and breast cancer diagnosis. The new datasets complement a significant update to the [HarvardX Data Science Professional Certificate Program](https://www.edx.org/professional-certificate/harvardx-data-science), where I wrote dozens of new problems to teach data science to new programmers through real-world case studies.


If you're interested in how the post was made, feel free to explore the [R markdown version on GitHub](https://github.com/gillsignals/science-docs/blob/master/simply-stats/more-datasets-simplystatistics.Rmd).

Many thanks to [Rafael Irizarry](http://rafalab.github.io/) for the opportunity to contribute to his data science educational materials and blog!